// Auto-generated by tools/convert.jl — registers all transpiled game scripts.
import "./Background";
import "./Fish";
import "./GameManager";
import "./PlayerMovement";
import "./Saw";
import "./Spider";
import "./Title";
import "./Water";
